// Auto-generated from repo/dex.h and official Korean names
const DEX_COUNT = 151;
const DEX_EEVEE = 133;
const R_EVO = 0, R_COMUN = 1, R_RARO = 2, R_LEGENDARIO = 3;
const DEX_TBL = [
  {
    "id": 0,
    "name": "?",
    "name_ko": "?",
    "name_ja": "?",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#292831",
    "accent565": 10566,
    "bHp": 50,
    "bAtk": 50,
    "bDef": 50,
    "bSpe": 50,
    "biome": 0
  },
  {
    "id": 1,
    "name": "BULBASAUR",
    "name_ko": "이상해씨",
    "name_ja": "フシギダネ",
    "evolvesTo": 2,
    "evolveLevel": 16,
    "rarity": 1,
    "accent": "#3a8a4a",
    "accent565": 15433,
    "bHp": 45,
    "bAtk": 49,
    "bDef": 49,
    "bSpe": 45,
    "biome": 2
  },
  {
    "id": 2,
    "name": "IVYSAUR",
    "name_ko": "이상해풀",
    "name_ja": "フシギソウ",
    "evolvesTo": 3,
    "evolveLevel": 32,
    "rarity": 0,
    "accent": "#3a8a4a",
    "accent565": 15433,
    "bHp": 60,
    "bAtk": 62,
    "bDef": 63,
    "bSpe": 60,
    "biome": 2
  },
  {
    "id": 3,
    "name": "VENUSAUR",
    "name_ko": "이상해꽃",
    "name_ja": "フシギバナ",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#3a8a4a",
    "accent565": 15433,
    "bHp": 80,
    "bAtk": 82,
    "bDef": 83,
    "bSpe": 80,
    "biome": 2
  },
  {
    "id": 4,
    "name": "CHARMANDER",
    "name_ko": "파이리",
    "name_ja": "ヒトカゲ",
    "evolvesTo": 5,
    "evolveLevel": 16,
    "rarity": 1,
    "accent": "#ef513a",
    "accent565": 60039,
    "bHp": 39,
    "bAtk": 52,
    "bDef": 43,
    "bSpe": 65,
    "biome": 3
  },
  {
    "id": 5,
    "name": "CHARMELEON",
    "name_ko": "리자드",
    "name_ja": "リザード",
    "evolvesTo": 6,
    "evolveLevel": 36,
    "rarity": 0,
    "accent": "#ef513a",
    "accent565": 60039,
    "bHp": 58,
    "bAtk": 64,
    "bDef": 58,
    "bSpe": 80,
    "biome": 3
  },
  {
    "id": 6,
    "name": "CHARIZARD",
    "name_ko": "리자몽",
    "name_ja": "リザードン",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#ef513a",
    "accent565": 60039,
    "bHp": 78,
    "bAtk": 84,
    "bDef": 78,
    "bSpe": 100,
    "biome": 3
  },
  {
    "id": 7,
    "name": "SQUIRTLE",
    "name_ko": "꼬부기",
    "name_ja": "ゼニガメ",
    "evolvesTo": 8,
    "evolveLevel": 16,
    "rarity": 1,
    "accent": "#4a92c5",
    "accent565": 19608,
    "bHp": 44,
    "bAtk": 48,
    "bDef": 65,
    "bSpe": 43,
    "biome": 1
  },
  {
    "id": 8,
    "name": "WARTORTLE",
    "name_ko": "어니부기",
    "name_ja": "カメール",
    "evolvesTo": 9,
    "evolveLevel": 36,
    "rarity": 0,
    "accent": "#4a92c5",
    "accent565": 19608,
    "bHp": 59,
    "bAtk": 63,
    "bDef": 80,
    "bSpe": 58,
    "biome": 1
  },
  {
    "id": 9,
    "name": "BLASTOISE",
    "name_ko": "거북왕",
    "name_ja": "カメックス",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#4a92c5",
    "accent565": 19608,
    "bHp": 79,
    "bAtk": 83,
    "bDef": 100,
    "bSpe": 78,
    "biome": 1
  },
  {
    "id": 10,
    "name": "CATERPIE",
    "name_ko": "캐터피",
    "name_ja": "キャタピー",
    "evolvesTo": 11,
    "evolveLevel": 7,
    "rarity": 1,
    "accent": "#7b9a21",
    "accent565": 31940,
    "bHp": 45,
    "bAtk": 30,
    "bDef": 35,
    "bSpe": 45,
    "biome": 2
  },
  {
    "id": 11,
    "name": "METAPOD",
    "name_ko": "단데기",
    "name_ja": "トランセル",
    "evolvesTo": 12,
    "evolveLevel": 10,
    "rarity": 0,
    "accent": "#7b9a21",
    "accent565": 31940,
    "bHp": 50,
    "bAtk": 20,
    "bDef": 55,
    "bSpe": 30,
    "biome": 2
  },
  {
    "id": 12,
    "name": "BUTTERFREE",
    "name_ko": "버터플",
    "name_ja": "バタフリー",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#7b9a21",
    "accent565": 31940,
    "bHp": 60,
    "bAtk": 45,
    "bDef": 50,
    "bSpe": 70,
    "biome": 2
  },
  {
    "id": 13,
    "name": "WEEDLE",
    "name_ko": "뿔충이",
    "name_ja": "ビードル",
    "evolvesTo": 14,
    "evolveLevel": 7,
    "rarity": 1,
    "accent": "#7b9a21",
    "accent565": 31940,
    "bHp": 40,
    "bAtk": 35,
    "bDef": 30,
    "bSpe": 50,
    "biome": 2
  },
  {
    "id": 14,
    "name": "KAKUNA",
    "name_ko": "딱충이",
    "name_ja": "コクーン",
    "evolvesTo": 15,
    "evolveLevel": 10,
    "rarity": 0,
    "accent": "#7b9a21",
    "accent565": 31940,
    "bHp": 45,
    "bAtk": 25,
    "bDef": 50,
    "bSpe": 35,
    "biome": 2
  },
  {
    "id": 15,
    "name": "BEEDRILL",
    "name_ko": "독침붕",
    "name_ja": "スピアー",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#7b9a21",
    "accent565": 31940,
    "bHp": 65,
    "bAtk": 90,
    "bDef": 40,
    "bSpe": 75,
    "biome": 2
  },
  {
    "id": 16,
    "name": "PIDGEY",
    "name_ko": "구구",
    "name_ja": "ポッポ",
    "evolvesTo": 17,
    "evolveLevel": 18,
    "rarity": 1,
    "accent": "#8c8a6b",
    "accent565": 35917,
    "bHp": 40,
    "bAtk": 45,
    "bDef": 40,
    "bSpe": 56,
    "biome": 0
  },
  {
    "id": 17,
    "name": "PIDGEOTTO",
    "name_ko": "피죤",
    "name_ja": "ピジョン",
    "evolvesTo": 18,
    "evolveLevel": 36,
    "rarity": 0,
    "accent": "#8c8a6b",
    "accent565": 35917,
    "bHp": 63,
    "bAtk": 60,
    "bDef": 55,
    "bSpe": 71,
    "biome": 0
  },
  {
    "id": 18,
    "name": "PIDGEOT",
    "name_ko": "피죤투",
    "name_ja": "ピジョット",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#8c8a6b",
    "accent565": 35917,
    "bHp": 83,
    "bAtk": 80,
    "bDef": 75,
    "bSpe": 101,
    "biome": 0
  },
  {
    "id": 19,
    "name": "RATTATA",
    "name_ko": "꼬렛",
    "name_ja": "コラッタ",
    "evolvesTo": 20,
    "evolveLevel": 20,
    "rarity": 1,
    "accent": "#8c8a6b",
    "accent565": 35917,
    "bHp": 30,
    "bAtk": 56,
    "bDef": 35,
    "bSpe": 72,
    "biome": 0
  },
  {
    "id": 20,
    "name": "RATICATE",
    "name_ko": "레트라",
    "name_ja": "ラッタ",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#8c8a6b",
    "accent565": 35917,
    "bHp": 55,
    "bAtk": 81,
    "bDef": 60,
    "bSpe": 97,
    "biome": 0
  },
  {
    "id": 21,
    "name": "SPEAROW",
    "name_ko": "깨비참",
    "name_ja": "オニスズメ",
    "evolvesTo": 22,
    "evolveLevel": 20,
    "rarity": 1,
    "accent": "#8c8a6b",
    "accent565": 35917,
    "bHp": 40,
    "bAtk": 60,
    "bDef": 30,
    "bSpe": 70,
    "biome": 0
  },
  {
    "id": 22,
    "name": "FEAROW",
    "name_ko": "깨비드릴조",
    "name_ja": "オニドリル",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#8c8a6b",
    "accent565": 35917,
    "bHp": 65,
    "bAtk": 90,
    "bDef": 65,
    "bSpe": 100,
    "biome": 0
  },
  {
    "id": 23,
    "name": "EKANS",
    "name_ko": "아보",
    "name_ja": "アーボ",
    "evolvesTo": 24,
    "evolveLevel": 22,
    "rarity": 1,
    "accent": "#8c4d9c",
    "accent565": 35443,
    "bHp": 35,
    "bAtk": 60,
    "bDef": 44,
    "bSpe": 55,
    "biome": 0
  },
  {
    "id": 24,
    "name": "ARBOK",
    "name_ko": "아보크",
    "name_ja": "アーボック",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#8c4d9c",
    "accent565": 35443,
    "bHp": 60,
    "bAtk": 95,
    "bDef": 69,
    "bSpe": 80,
    "biome": 0
  },
  {
    "id": 25,
    "name": "PIKACHU",
    "name_ko": "피카츄",
    "name_ja": "ピカチュウ",
    "evolvesTo": 26,
    "evolveLevel": 30,
    "rarity": 1,
    "accent": "#bd9608",
    "accent565": 48289,
    "bHp": 35,
    "bAtk": 55,
    "bDef": 40,
    "bSpe": 90,
    "biome": 0
  },
  {
    "id": 26,
    "name": "RAICHU",
    "name_ko": "라이츄",
    "name_ja": "ライチュウ",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#bd9608",
    "accent565": 48289,
    "bHp": 60,
    "bAtk": 90,
    "bDef": 55,
    "bSpe": 110,
    "biome": 0
  },
  {
    "id": 27,
    "name": "SANDSHREW",
    "name_ko": "모래두지",
    "name_ja": "サンド",
    "evolvesTo": 28,
    "evolveLevel": 22,
    "rarity": 1,
    "accent": "#b58a3a",
    "accent565": 46151,
    "bHp": 50,
    "bAtk": 75,
    "bDef": 85,
    "bSpe": 40,
    "biome": 4
  },
  {
    "id": 28,
    "name": "SANDSLASH",
    "name_ko": "고지",
    "name_ja": "サンドパン",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#b58a3a",
    "accent565": 46151,
    "bHp": 75,
    "bAtk": 100,
    "bDef": 110,
    "bSpe": 65,
    "biome": 4
  },
  {
    "id": 29,
    "name": "NIDORAN H",
    "name_ko": "니드런♀",
    "name_ja": "ニドラン♀",
    "evolvesTo": 30,
    "evolveLevel": 16,
    "rarity": 1,
    "accent": "#8c4d9c",
    "accent565": 35443,
    "bHp": 55,
    "bAtk": 47,
    "bDef": 52,
    "bSpe": 41,
    "biome": 0
  },
  {
    "id": 30,
    "name": "NIDORINA",
    "name_ko": "니드리나",
    "name_ja": "ニドリーナ",
    "evolvesTo": 31,
    "evolveLevel": 30,
    "rarity": 0,
    "accent": "#8c4d9c",
    "accent565": 35443,
    "bHp": 70,
    "bAtk": 62,
    "bDef": 67,
    "bSpe": 56,
    "biome": 0
  },
  {
    "id": 31,
    "name": "NIDOQUEEN",
    "name_ko": "니드퀸",
    "name_ja": "ニドクイン",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#8c4d9c",
    "accent565": 35443,
    "bHp": 90,
    "bAtk": 92,
    "bDef": 87,
    "bSpe": 76,
    "biome": 0
  },
  {
    "id": 32,
    "name": "NIDORAN M",
    "name_ko": "니드런♂",
    "name_ja": "ニドラン♂",
    "evolvesTo": 33,
    "evolveLevel": 16,
    "rarity": 1,
    "accent": "#8c4d9c",
    "accent565": 35443,
    "bHp": 46,
    "bAtk": 57,
    "bDef": 40,
    "bSpe": 50,
    "biome": 0
  },
  {
    "id": 33,
    "name": "NIDORINO",
    "name_ko": "니드리노",
    "name_ja": "ニドリーノ",
    "evolvesTo": 34,
    "evolveLevel": 30,
    "rarity": 0,
    "accent": "#8c4d9c",
    "accent565": 35443,
    "bHp": 61,
    "bAtk": 72,
    "bDef": 57,
    "bSpe": 65,
    "biome": 0
  },
  {
    "id": 34,
    "name": "NIDOKING",
    "name_ko": "니드킹",
    "name_ja": "ニドキング",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#8c4d9c",
    "accent565": 35443,
    "bHp": 81,
    "bAtk": 102,
    "bDef": 77,
    "bSpe": 85,
    "biome": 0
  },
  {
    "id": 35,
    "name": "CLEFAIRY",
    "name_ko": "삐삐",
    "name_ja": "ピッピ",
    "evolvesTo": 36,
    "evolveLevel": 30,
    "rarity": 1,
    "accent": "#8c8a6b",
    "accent565": 35917,
    "bHp": 70,
    "bAtk": 45,
    "bDef": 48,
    "bSpe": 35,
    "biome": 0
  },
  {
    "id": 36,
    "name": "CLEFABLE",
    "name_ko": "픽시",
    "name_ja": "ピクシー",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#8c8a6b",
    "accent565": 35917,
    "bHp": 95,
    "bAtk": 70,
    "bDef": 73,
    "bSpe": 60,
    "biome": 0
  },
  {
    "id": 37,
    "name": "VULPIX",
    "name_ko": "식스테일",
    "name_ja": "ロコン",
    "evolvesTo": 38,
    "evolveLevel": 30,
    "rarity": 1,
    "accent": "#ef513a",
    "accent565": 60039,
    "bHp": 38,
    "bAtk": 41,
    "bDef": 40,
    "bSpe": 65,
    "biome": 3
  },
  {
    "id": 38,
    "name": "NINETALES",
    "name_ko": "나인테일",
    "name_ja": "キュウコン",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#ef513a",
    "accent565": 60039,
    "bHp": 73,
    "bAtk": 76,
    "bDef": 75,
    "bSpe": 100,
    "biome": 3
  },
  {
    "id": 39,
    "name": "JIGGLYPUFF",
    "name_ko": "푸린",
    "name_ja": "プリン",
    "evolvesTo": 40,
    "evolveLevel": 30,
    "rarity": 1,
    "accent": "#8c8a6b",
    "accent565": 35917,
    "bHp": 115,
    "bAtk": 45,
    "bDef": 20,
    "bSpe": 20,
    "biome": 0
  },
  {
    "id": 40,
    "name": "WIGGLYTUFF",
    "name_ko": "푸크린",
    "name_ja": "プクリン",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#8c8a6b",
    "accent565": 35917,
    "bHp": 140,
    "bAtk": 70,
    "bDef": 45,
    "bSpe": 45,
    "biome": 0
  },
  {
    "id": 41,
    "name": "ZUBAT",
    "name_ko": "주뱃",
    "name_ja": "ズバット",
    "evolvesTo": 42,
    "evolveLevel": 22,
    "rarity": 1,
    "accent": "#8c4d9c",
    "accent565": 35443,
    "bHp": 40,
    "bAtk": 45,
    "bDef": 35,
    "bSpe": 55,
    "biome": 0
  },
  {
    "id": 42,
    "name": "GOLBAT",
    "name_ko": "골뱃",
    "name_ja": "ゴルバット",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#8c4d9c",
    "accent565": 35443,
    "bHp": 75,
    "bAtk": 80,
    "bDef": 70,
    "bSpe": 90,
    "biome": 0
  },
  {
    "id": 43,
    "name": "ODDISH",
    "name_ko": "뚜벅쵸",
    "name_ja": "ナゾノクサ",
    "evolvesTo": 44,
    "evolveLevel": 21,
    "rarity": 1,
    "accent": "#3a8a4a",
    "accent565": 15433,
    "bHp": 45,
    "bAtk": 50,
    "bDef": 55,
    "bSpe": 30,
    "biome": 2
  },
  {
    "id": 44,
    "name": "GLOOM",
    "name_ko": "냄새꼬",
    "name_ja": "クサイハナ",
    "evolvesTo": 45,
    "evolveLevel": 36,
    "rarity": 0,
    "accent": "#3a8a4a",
    "accent565": 15433,
    "bHp": 60,
    "bAtk": 65,
    "bDef": 70,
    "bSpe": 40,
    "biome": 2
  },
  {
    "id": 45,
    "name": "VILEPLUME",
    "name_ko": "라플레시아",
    "name_ja": "ラフレシア",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#3a8a4a",
    "accent565": 15433,
    "bHp": 75,
    "bAtk": 80,
    "bDef": 85,
    "bSpe": 50,
    "biome": 2
  },
  {
    "id": 46,
    "name": "PARAS",
    "name_ko": "파라스",
    "name_ja": "パラス",
    "evolvesTo": 47,
    "evolveLevel": 24,
    "rarity": 1,
    "accent": "#7b9a21",
    "accent565": 31940,
    "bHp": 35,
    "bAtk": 70,
    "bDef": 55,
    "bSpe": 25,
    "biome": 2
  },
  {
    "id": 47,
    "name": "PARASECT",
    "name_ko": "파라섹트",
    "name_ja": "パラセクト",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#7b9a21",
    "accent565": 31940,
    "bHp": 60,
    "bAtk": 95,
    "bDef": 80,
    "bSpe": 30,
    "biome": 2
  },
  {
    "id": 48,
    "name": "VENONAT",
    "name_ko": "콘팡",
    "name_ja": "コンパン",
    "evolvesTo": 49,
    "evolveLevel": 31,
    "rarity": 1,
    "accent": "#7b9a21",
    "accent565": 31940,
    "bHp": 60,
    "bAtk": 55,
    "bDef": 50,
    "bSpe": 45,
    "biome": 2
  },
  {
    "id": 49,
    "name": "VENOMOTH",
    "name_ko": "도나리",
    "name_ja": "モルフォン",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#7b9a21",
    "accent565": 31940,
    "bHp": 70,
    "bAtk": 65,
    "bDef": 60,
    "bSpe": 90,
    "biome": 2
  },
  {
    "id": 50,
    "name": "DIGLETT",
    "name_ko": "디그다",
    "name_ja": "ディグダ",
    "evolvesTo": 51,
    "evolveLevel": 26,
    "rarity": 1,
    "accent": "#b58a3a",
    "accent565": 46151,
    "bHp": 10,
    "bAtk": 55,
    "bDef": 25,
    "bSpe": 95,
    "biome": 4
  },
  {
    "id": 51,
    "name": "DUGTRIO",
    "name_ko": "닥트리오",
    "name_ja": "ダグトリオ",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#b58a3a",
    "accent565": 46151,
    "bHp": 35,
    "bAtk": 100,
    "bDef": 50,
    "bSpe": 120,
    "biome": 4
  },
  {
    "id": 52,
    "name": "MEOWTH",
    "name_ko": "나옹",
    "name_ja": "ニャース",
    "evolvesTo": 53,
    "evolveLevel": 28,
    "rarity": 1,
    "accent": "#8c8a6b",
    "accent565": 35917,
    "bHp": 40,
    "bAtk": 45,
    "bDef": 35,
    "bSpe": 90,
    "biome": 0
  },
  {
    "id": 53,
    "name": "PERSIAN",
    "name_ko": "페르시온",
    "name_ja": "ペルシアン",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#8c8a6b",
    "accent565": 35917,
    "bHp": 65,
    "bAtk": 70,
    "bDef": 60,
    "bSpe": 115,
    "biome": 0
  },
  {
    "id": 54,
    "name": "PSYDUCK",
    "name_ko": "고라파덕",
    "name_ja": "コダック",
    "evolvesTo": 55,
    "evolveLevel": 33,
    "rarity": 1,
    "accent": "#4a92c5",
    "accent565": 19608,
    "bHp": 50,
    "bAtk": 52,
    "bDef": 48,
    "bSpe": 55,
    "biome": 1
  },
  {
    "id": 55,
    "name": "GOLDUCK",
    "name_ko": "골덕",
    "name_ja": "ゴルダック",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#4a92c5",
    "accent565": 19608,
    "bHp": 80,
    "bAtk": 82,
    "bDef": 78,
    "bSpe": 85,
    "biome": 1
  },
  {
    "id": 56,
    "name": "MANKEY",
    "name_ko": "망키",
    "name_ja": "マンキー",
    "evolvesTo": 57,
    "evolveLevel": 28,
    "rarity": 1,
    "accent": "#a55529",
    "accent565": 41637,
    "bHp": 40,
    "bAtk": 80,
    "bDef": 35,
    "bSpe": 70,
    "biome": 0
  },
  {
    "id": 57,
    "name": "PRIMEAPE",
    "name_ko": "성원숭",
    "name_ja": "オコリザル",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#a55529",
    "accent565": 41637,
    "bHp": 65,
    "bAtk": 105,
    "bDef": 60,
    "bSpe": 95,
    "biome": 0
  },
  {
    "id": 58,
    "name": "GROWLITHE",
    "name_ko": "가디",
    "name_ja": "ガーディ",
    "evolvesTo": 59,
    "evolveLevel": 30,
    "rarity": 2,
    "accent": "#ef513a",
    "accent565": 60039,
    "bHp": 55,
    "bAtk": 70,
    "bDef": 45,
    "bSpe": 60,
    "biome": 3
  },
  {
    "id": 59,
    "name": "ARCANINE",
    "name_ko": "윈디",
    "name_ja": "ウインディ",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#ef513a",
    "accent565": 60039,
    "bHp": 90,
    "bAtk": 110,
    "bDef": 80,
    "bSpe": 95,
    "biome": 3
  },
  {
    "id": 60,
    "name": "POLIWAG",
    "name_ko": "발챙이",
    "name_ja": "ニョロモ",
    "evolvesTo": 61,
    "evolveLevel": 25,
    "rarity": 1,
    "accent": "#4a92c5",
    "accent565": 19608,
    "bHp": 40,
    "bAtk": 50,
    "bDef": 40,
    "bSpe": 90,
    "biome": 1
  },
  {
    "id": 61,
    "name": "POLIWHIRL",
    "name_ko": "슈륙챙이",
    "name_ja": "ニョロゾ",
    "evolvesTo": 62,
    "evolveLevel": 36,
    "rarity": 0,
    "accent": "#4a92c5",
    "accent565": 19608,
    "bHp": 65,
    "bAtk": 65,
    "bDef": 65,
    "bSpe": 90,
    "biome": 1
  },
  {
    "id": 62,
    "name": "POLIWRATH",
    "name_ko": "강챙이",
    "name_ja": "ニョロボン",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#4a92c5",
    "accent565": 19608,
    "bHp": 90,
    "bAtk": 95,
    "bDef": 95,
    "bSpe": 70,
    "biome": 1
  },
  {
    "id": 63,
    "name": "ABRA",
    "name_ko": "케이시",
    "name_ja": "ケーシィ",
    "evolvesTo": 64,
    "evolveLevel": 16,
    "rarity": 1,
    "accent": "#d6517b",
    "accent565": 53903,
    "bHp": 25,
    "bAtk": 20,
    "bDef": 15,
    "bSpe": 90,
    "biome": 0
  },
  {
    "id": 64,
    "name": "KADABRA",
    "name_ko": "윤겔라",
    "name_ja": "ユンゲラー",
    "evolvesTo": 65,
    "evolveLevel": 40,
    "rarity": 0,
    "accent": "#d6517b",
    "accent565": 53903,
    "bHp": 40,
    "bAtk": 35,
    "bDef": 30,
    "bSpe": 105,
    "biome": 0
  },
  {
    "id": 65,
    "name": "ALAKAZAM",
    "name_ko": "후딘",
    "name_ja": "フーディン",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#d6517b",
    "accent565": 53903,
    "bHp": 55,
    "bAtk": 50,
    "bDef": 45,
    "bSpe": 120,
    "biome": 0
  },
  {
    "id": 66,
    "name": "MACHOP",
    "name_ko": "알통몬",
    "name_ja": "ワンリキー",
    "evolvesTo": 67,
    "evolveLevel": 28,
    "rarity": 1,
    "accent": "#a55529",
    "accent565": 41637,
    "bHp": 70,
    "bAtk": 80,
    "bDef": 50,
    "bSpe": 35,
    "biome": 0
  },
  {
    "id": 67,
    "name": "MACHOKE",
    "name_ko": "근육몬",
    "name_ja": "ゴーリキー",
    "evolvesTo": 68,
    "evolveLevel": 40,
    "rarity": 0,
    "accent": "#a55529",
    "accent565": 41637,
    "bHp": 80,
    "bAtk": 100,
    "bDef": 70,
    "bSpe": 45,
    "biome": 0
  },
  {
    "id": 68,
    "name": "MACHAMP",
    "name_ko": "괴력몬",
    "name_ja": "カイリキー",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#a55529",
    "accent565": 41637,
    "bHp": 90,
    "bAtk": 130,
    "bDef": 80,
    "bSpe": 55,
    "biome": 0
  },
  {
    "id": 69,
    "name": "BELLSPROUT",
    "name_ko": "모다피",
    "name_ja": "マダツボミ",
    "evolvesTo": 70,
    "evolveLevel": 21,
    "rarity": 1,
    "accent": "#3a8a4a",
    "accent565": 15433,
    "bHp": 50,
    "bAtk": 75,
    "bDef": 35,
    "bSpe": 40,
    "biome": 2
  },
  {
    "id": 70,
    "name": "WEEPINBELL",
    "name_ko": "우츠동",
    "name_ja": "ウツドン",
    "evolvesTo": 71,
    "evolveLevel": 36,
    "rarity": 0,
    "accent": "#3a8a4a",
    "accent565": 15433,
    "bHp": 65,
    "bAtk": 90,
    "bDef": 50,
    "bSpe": 55,
    "biome": 2
  },
  {
    "id": 71,
    "name": "VICTREEBEL",
    "name_ko": "우츠보트",
    "name_ja": "ウツボット",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#3a8a4a",
    "accent565": 15433,
    "bHp": 80,
    "bAtk": 105,
    "bDef": 65,
    "bSpe": 70,
    "biome": 2
  },
  {
    "id": 72,
    "name": "TENTACOOL",
    "name_ko": "왕눈해",
    "name_ja": "メノクラゲ",
    "evolvesTo": 73,
    "evolveLevel": 30,
    "rarity": 1,
    "accent": "#4a92c5",
    "accent565": 19608,
    "bHp": 40,
    "bAtk": 40,
    "bDef": 35,
    "bSpe": 70,
    "biome": 1
  },
  {
    "id": 73,
    "name": "TENTACRUEL",
    "name_ko": "독파리",
    "name_ja": "ドククラゲ",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#4a92c5",
    "accent565": 19608,
    "bHp": 80,
    "bAtk": 70,
    "bDef": 65,
    "bSpe": 100,
    "biome": 1
  },
  {
    "id": 74,
    "name": "GEODUDE",
    "name_ko": "꼬마돌",
    "name_ja": "イシツブテ",
    "evolvesTo": 75,
    "evolveLevel": 25,
    "rarity": 1,
    "accent": "#94823a",
    "accent565": 37895,
    "bHp": 40,
    "bAtk": 80,
    "bDef": 100,
    "bSpe": 20,
    "biome": 4
  },
  {
    "id": 75,
    "name": "GRAVELER",
    "name_ko": "데구리",
    "name_ja": "ゴローン",
    "evolvesTo": 76,
    "evolveLevel": 40,
    "rarity": 0,
    "accent": "#94823a",
    "accent565": 37895,
    "bHp": 55,
    "bAtk": 95,
    "bDef": 115,
    "bSpe": 35,
    "biome": 4
  },
  {
    "id": 76,
    "name": "GOLEM",
    "name_ko": "딱구리",
    "name_ja": "ゴローニャ",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#94823a",
    "accent565": 37895,
    "bHp": 80,
    "bAtk": 120,
    "bDef": 130,
    "bSpe": 45,
    "biome": 4
  },
  {
    "id": 77,
    "name": "PONYTA",
    "name_ko": "포니타",
    "name_ja": "ポニータ",
    "evolvesTo": 78,
    "evolveLevel": 40,
    "rarity": 2,
    "accent": "#ef513a",
    "accent565": 60039,
    "bHp": 50,
    "bAtk": 85,
    "bDef": 55,
    "bSpe": 90,
    "biome": 3
  },
  {
    "id": 78,
    "name": "RAPIDASH",
    "name_ko": "날쌩마",
    "name_ja": "ギャロップ",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#ef513a",
    "accent565": 60039,
    "bHp": 65,
    "bAtk": 100,
    "bDef": 70,
    "bSpe": 105,
    "biome": 3
  },
  {
    "id": 79,
    "name": "SLOWPOKE",
    "name_ko": "야돈",
    "name_ja": "ヤドン",
    "evolvesTo": 80,
    "evolveLevel": 37,
    "rarity": 1,
    "accent": "#4a92c5",
    "accent565": 19608,
    "bHp": 90,
    "bAtk": 65,
    "bDef": 65,
    "bSpe": 15,
    "biome": 1
  },
  {
    "id": 80,
    "name": "SLOWBRO",
    "name_ko": "야도란",
    "name_ja": "ヤドラン",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#4a92c5",
    "accent565": 19608,
    "bHp": 95,
    "bAtk": 75,
    "bDef": 110,
    "bSpe": 30,
    "biome": 1
  },
  {
    "id": 81,
    "name": "MAGNEMITE",
    "name_ko": "코일",
    "name_ja": "コイル",
    "evolvesTo": 82,
    "evolveLevel": 30,
    "rarity": 1,
    "accent": "#bd9608",
    "accent565": 48289,
    "bHp": 25,
    "bAtk": 35,
    "bDef": 70,
    "bSpe": 45,
    "biome": 0
  },
  {
    "id": 82,
    "name": "MAGNETON",
    "name_ko": "레어코일",
    "name_ja": "レアコイル",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#bd9608",
    "accent565": 48289,
    "bHp": 50,
    "bAtk": 60,
    "bDef": 95,
    "bSpe": 70,
    "biome": 0
  },
  {
    "id": 83,
    "name": "FARFETCHD",
    "name_ko": "파오리",
    "name_ja": "カモネギ",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 2,
    "accent": "#8c8a6b",
    "accent565": 35917,
    "bHp": 52,
    "bAtk": 90,
    "bDef": 55,
    "bSpe": 60,
    "biome": 0
  },
  {
    "id": 84,
    "name": "DODUO",
    "name_ko": "두두",
    "name_ja": "ドードー",
    "evolvesTo": 85,
    "evolveLevel": 31,
    "rarity": 1,
    "accent": "#8c8a6b",
    "accent565": 35917,
    "bHp": 35,
    "bAtk": 85,
    "bDef": 45,
    "bSpe": 75,
    "biome": 0
  },
  {
    "id": 85,
    "name": "DODRIO",
    "name_ko": "두트리오",
    "name_ja": "ドードリオ",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#8c8a6b",
    "accent565": 35917,
    "bHp": 60,
    "bAtk": 110,
    "bDef": 70,
    "bSpe": 110,
    "biome": 0
  },
  {
    "id": 86,
    "name": "SEEL",
    "name_ko": "쥬쥬",
    "name_ja": "パウワウ",
    "evolvesTo": 87,
    "evolveLevel": 34,
    "rarity": 1,
    "accent": "#4a92c5",
    "accent565": 19608,
    "bHp": 65,
    "bAtk": 45,
    "bDef": 55,
    "bSpe": 45,
    "biome": 1
  },
  {
    "id": 87,
    "name": "DEWGONG",
    "name_ko": "쥬레곤",
    "name_ja": "ジュゴン",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#4a92c5",
    "accent565": 19608,
    "bHp": 90,
    "bAtk": 70,
    "bDef": 80,
    "bSpe": 70,
    "biome": 1
  },
  {
    "id": 88,
    "name": "GRIMER",
    "name_ko": "질퍽이",
    "name_ja": "ベトベター",
    "evolvesTo": 89,
    "evolveLevel": 38,
    "rarity": 2,
    "accent": "#8c4d9c",
    "accent565": 35443,
    "bHp": 80,
    "bAtk": 80,
    "bDef": 50,
    "bSpe": 25,
    "biome": 0
  },
  {
    "id": 89,
    "name": "MUK",
    "name_ko": "질뻐기",
    "name_ja": "ベトベトン",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#8c4d9c",
    "accent565": 35443,
    "bHp": 105,
    "bAtk": 105,
    "bDef": 75,
    "bSpe": 50,
    "biome": 0
  },
  {
    "id": 90,
    "name": "SHELLDER",
    "name_ko": "셀러",
    "name_ja": "シェルダー",
    "evolvesTo": 91,
    "evolveLevel": 30,
    "rarity": 1,
    "accent": "#4a92c5",
    "accent565": 19608,
    "bHp": 30,
    "bAtk": 65,
    "bDef": 100,
    "bSpe": 40,
    "biome": 1
  },
  {
    "id": 91,
    "name": "CLOYSTER",
    "name_ko": "파르셀",
    "name_ja": "パルシェン",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#4a92c5",
    "accent565": 19608,
    "bHp": 50,
    "bAtk": 95,
    "bDef": 180,
    "bSpe": 70,
    "biome": 1
  },
  {
    "id": 92,
    "name": "GASTLY",
    "name_ko": "고오스",
    "name_ja": "ゴース",
    "evolvesTo": 93,
    "evolveLevel": 25,
    "rarity": 1,
    "accent": "#6b599c",
    "accent565": 27347,
    "bHp": 30,
    "bAtk": 35,
    "bDef": 30,
    "bSpe": 80,
    "biome": 0
  },
  {
    "id": 93,
    "name": "HAUNTER",
    "name_ko": "고우스트",
    "name_ja": "ゴースト",
    "evolvesTo": 94,
    "evolveLevel": 40,
    "rarity": 0,
    "accent": "#6b599c",
    "accent565": 27347,
    "bHp": 45,
    "bAtk": 50,
    "bDef": 45,
    "bSpe": 95,
    "biome": 0
  },
  {
    "id": 94,
    "name": "GENGAR",
    "name_ko": "팬텀",
    "name_ja": "ゲンガー",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#6b599c",
    "accent565": 27347,
    "bHp": 60,
    "bAtk": 65,
    "bDef": 60,
    "bSpe": 110,
    "biome": 0
  },
  {
    "id": 95,
    "name": "ONIX",
    "name_ko": "롱스톤",
    "name_ja": "イワーク",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 2,
    "accent": "#94823a",
    "accent565": 37895,
    "bHp": 35,
    "bAtk": 45,
    "bDef": 160,
    "bSpe": 70,
    "biome": 4
  },
  {
    "id": 96,
    "name": "DROWZEE",
    "name_ko": "슬리프",
    "name_ja": "スリープ",
    "evolvesTo": 97,
    "evolveLevel": 26,
    "rarity": 1,
    "accent": "#d6517b",
    "accent565": 53903,
    "bHp": 60,
    "bAtk": 48,
    "bDef": 45,
    "bSpe": 42,
    "biome": 0
  },
  {
    "id": 97,
    "name": "HYPNO",
    "name_ko": "슬리퍼",
    "name_ja": "スリーパー",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#d6517b",
    "accent565": 53903,
    "bHp": 85,
    "bAtk": 73,
    "bDef": 70,
    "bSpe": 67,
    "biome": 0
  },
  {
    "id": 98,
    "name": "KRABBY",
    "name_ko": "크랩",
    "name_ja": "クラブ",
    "evolvesTo": 99,
    "evolveLevel": 28,
    "rarity": 1,
    "accent": "#4a92c5",
    "accent565": 19608,
    "bHp": 30,
    "bAtk": 105,
    "bDef": 90,
    "bSpe": 50,
    "biome": 1
  },
  {
    "id": 99,
    "name": "KINGLER",
    "name_ko": "킹크랩",
    "name_ja": "キングラー",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#4a92c5",
    "accent565": 19608,
    "bHp": 55,
    "bAtk": 130,
    "bDef": 115,
    "bSpe": 75,
    "biome": 1
  },
  {
    "id": 100,
    "name": "VOLTORB",
    "name_ko": "찌리리공",
    "name_ja": "ビリリダマ",
    "evolvesTo": 101,
    "evolveLevel": 30,
    "rarity": 1,
    "accent": "#bd9608",
    "accent565": 48289,
    "bHp": 40,
    "bAtk": 30,
    "bDef": 50,
    "bSpe": 100,
    "biome": 0
  },
  {
    "id": 101,
    "name": "ELECTRODE",
    "name_ko": "붐볼",
    "name_ja": "マルマイン",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#bd9608",
    "accent565": 48289,
    "bHp": 60,
    "bAtk": 50,
    "bDef": 70,
    "bSpe": 150,
    "biome": 0
  },
  {
    "id": 102,
    "name": "EXEGGCUTE",
    "name_ko": "아라리",
    "name_ja": "タマタマ",
    "evolvesTo": 103,
    "evolveLevel": 30,
    "rarity": 1,
    "accent": "#3a8a4a",
    "accent565": 15433,
    "bHp": 60,
    "bAtk": 40,
    "bDef": 80,
    "bSpe": 40,
    "biome": 2
  },
  {
    "id": 103,
    "name": "EXEGGUTOR",
    "name_ko": "나시",
    "name_ja": "ナッシー",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#3a8a4a",
    "accent565": 15433,
    "bHp": 95,
    "bAtk": 95,
    "bDef": 85,
    "bSpe": 55,
    "biome": 2
  },
  {
    "id": 104,
    "name": "CUBONE",
    "name_ko": "탕구리",
    "name_ja": "カラカラ",
    "evolvesTo": 105,
    "evolveLevel": 28,
    "rarity": 1,
    "accent": "#b58a3a",
    "accent565": 46151,
    "bHp": 50,
    "bAtk": 50,
    "bDef": 95,
    "bSpe": 35,
    "biome": 4
  },
  {
    "id": 105,
    "name": "MAROWAK",
    "name_ko": "텅구리",
    "name_ja": "ガラガラ",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#b58a3a",
    "accent565": 46151,
    "bHp": 60,
    "bAtk": 80,
    "bDef": 110,
    "bSpe": 45,
    "biome": 4
  },
  {
    "id": 106,
    "name": "HITMONLEE",
    "name_ko": "시라소몬",
    "name_ja": "サワムラー",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 2,
    "accent": "#a55529",
    "accent565": 41637,
    "bHp": 50,
    "bAtk": 120,
    "bDef": 53,
    "bSpe": 87,
    "biome": 0
  },
  {
    "id": 107,
    "name": "HITMONCHAN",
    "name_ko": "홍수몬",
    "name_ja": "エビワラー",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 2,
    "accent": "#a55529",
    "accent565": 41637,
    "bHp": 50,
    "bAtk": 105,
    "bDef": 79,
    "bSpe": 76,
    "biome": 0
  },
  {
    "id": 108,
    "name": "LICKITUNG",
    "name_ko": "내루미",
    "name_ja": "ベロリンガ",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 2,
    "accent": "#8c8a6b",
    "accent565": 35917,
    "bHp": 90,
    "bAtk": 55,
    "bDef": 75,
    "bSpe": 30,
    "biome": 0
  },
  {
    "id": 109,
    "name": "KOFFING",
    "name_ko": "또가스",
    "name_ja": "ドガース",
    "evolvesTo": 110,
    "evolveLevel": 35,
    "rarity": 1,
    "accent": "#8c4d9c",
    "accent565": 35443,
    "bHp": 40,
    "bAtk": 65,
    "bDef": 95,
    "bSpe": 35,
    "biome": 0
  },
  {
    "id": 110,
    "name": "WEEZING",
    "name_ko": "또도가스",
    "name_ja": "マタドガス",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#8c4d9c",
    "accent565": 35443,
    "bHp": 65,
    "bAtk": 90,
    "bDef": 120,
    "bSpe": 60,
    "biome": 0
  },
  {
    "id": 111,
    "name": "RHYHORN",
    "name_ko": "뿔카노",
    "name_ja": "サイホーン",
    "evolvesTo": 112,
    "evolveLevel": 42,
    "rarity": 2,
    "accent": "#b58a3a",
    "accent565": 46151,
    "bHp": 80,
    "bAtk": 85,
    "bDef": 95,
    "bSpe": 25,
    "biome": 4
  },
  {
    "id": 112,
    "name": "RHYDON",
    "name_ko": "코뿌리",
    "name_ja": "サイドン",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#b58a3a",
    "accent565": 46151,
    "bHp": 105,
    "bAtk": 130,
    "bDef": 120,
    "bSpe": 40,
    "biome": 4
  },
  {
    "id": 113,
    "name": "CHANSEY",
    "name_ko": "럭키",
    "name_ja": "ラッキー",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 2,
    "accent": "#8c8a6b",
    "accent565": 35917,
    "bHp": 250,
    "bAtk": 5,
    "bDef": 5,
    "bSpe": 50,
    "biome": 0
  },
  {
    "id": 114,
    "name": "TANGELA",
    "name_ko": "덩쿠리",
    "name_ja": "モンジャラ",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 2,
    "accent": "#3a8a4a",
    "accent565": 15433,
    "bHp": 65,
    "bAtk": 55,
    "bDef": 115,
    "bSpe": 60,
    "biome": 2
  },
  {
    "id": 115,
    "name": "KANGASKHAN",
    "name_ko": "캥카",
    "name_ja": "ガルーラ",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 2,
    "accent": "#8c8a6b",
    "accent565": 35917,
    "bHp": 105,
    "bAtk": 95,
    "bDef": 80,
    "bSpe": 90,
    "biome": 0
  },
  {
    "id": 116,
    "name": "HORSEA",
    "name_ko": "쏘드라",
    "name_ja": "タッツー",
    "evolvesTo": 117,
    "evolveLevel": 32,
    "rarity": 1,
    "accent": "#4a92c5",
    "accent565": 19608,
    "bHp": 30,
    "bAtk": 40,
    "bDef": 70,
    "bSpe": 60,
    "biome": 1
  },
  {
    "id": 117,
    "name": "SEADRA",
    "name_ko": "시드라",
    "name_ja": "シードラ",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#4a92c5",
    "accent565": 19608,
    "bHp": 55,
    "bAtk": 65,
    "bDef": 95,
    "bSpe": 85,
    "biome": 1
  },
  {
    "id": 118,
    "name": "GOLDEEN",
    "name_ko": "콘치",
    "name_ja": "トサキント",
    "evolvesTo": 119,
    "evolveLevel": 33,
    "rarity": 1,
    "accent": "#4a92c5",
    "accent565": 19608,
    "bHp": 45,
    "bAtk": 67,
    "bDef": 60,
    "bSpe": 63,
    "biome": 1
  },
  {
    "id": 119,
    "name": "SEAKING",
    "name_ko": "왕콘치",
    "name_ja": "アズマオウ",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#4a92c5",
    "accent565": 19608,
    "bHp": 80,
    "bAtk": 92,
    "bDef": 65,
    "bSpe": 68,
    "biome": 1
  },
  {
    "id": 120,
    "name": "STARYU",
    "name_ko": "별가사리",
    "name_ja": "ヒトデマン",
    "evolvesTo": 121,
    "evolveLevel": 30,
    "rarity": 1,
    "accent": "#4a92c5",
    "accent565": 19608,
    "bHp": 30,
    "bAtk": 45,
    "bDef": 55,
    "bSpe": 85,
    "biome": 1
  },
  {
    "id": 121,
    "name": "STARMIE",
    "name_ko": "아쿠스타",
    "name_ja": "スターミー",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#4a92c5",
    "accent565": 19608,
    "bHp": 60,
    "bAtk": 75,
    "bDef": 85,
    "bSpe": 115,
    "biome": 1
  },
  {
    "id": 122,
    "name": "MR. MIME",
    "name_ko": "마임맨",
    "name_ja": "バリヤード",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 2,
    "accent": "#d6517b",
    "accent565": 53903,
    "bHp": 40,
    "bAtk": 45,
    "bDef": 65,
    "bSpe": 90,
    "biome": 0
  },
  {
    "id": 123,
    "name": "SCYTHER",
    "name_ko": "스라크",
    "name_ja": "ストライク",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 2,
    "accent": "#7b9a21",
    "accent565": 31940,
    "bHp": 70,
    "bAtk": 110,
    "bDef": 80,
    "bSpe": 105,
    "biome": 2
  },
  {
    "id": 124,
    "name": "JYNX",
    "name_ko": "루주라",
    "name_ja": "ルージュラ",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 2,
    "accent": "#4ab6c5",
    "accent565": 19896,
    "bHp": 65,
    "bAtk": 50,
    "bDef": 35,
    "bSpe": 95,
    "biome": 5
  },
  {
    "id": 125,
    "name": "ELECTABUZZ",
    "name_ko": "에레브",
    "name_ja": "エレブー",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 2,
    "accent": "#bd9608",
    "accent565": 48289,
    "bHp": 65,
    "bAtk": 83,
    "bDef": 57,
    "bSpe": 105,
    "biome": 0
  },
  {
    "id": 126,
    "name": "MAGMAR",
    "name_ko": "마그마",
    "name_ja": "ブーバー",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 2,
    "accent": "#ef513a",
    "accent565": 60039,
    "bHp": 65,
    "bAtk": 95,
    "bDef": 57,
    "bSpe": 93,
    "biome": 3
  },
  {
    "id": 127,
    "name": "PINSIR",
    "name_ko": "쁘사이저",
    "name_ja": "カイロス",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 2,
    "accent": "#7b9a21",
    "accent565": 31940,
    "bHp": 65,
    "bAtk": 125,
    "bDef": 100,
    "bSpe": 85,
    "biome": 2
  },
  {
    "id": 128,
    "name": "TAUROS",
    "name_ko": "켄타로스",
    "name_ja": "ケンタロス",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 2,
    "accent": "#8c8a6b",
    "accent565": 35917,
    "bHp": 75,
    "bAtk": 100,
    "bDef": 95,
    "bSpe": 110,
    "biome": 0
  },
  {
    "id": 129,
    "name": "MAGIKARP",
    "name_ko": "잉어킹",
    "name_ja": "コイキング",
    "evolvesTo": 130,
    "evolveLevel": 20,
    "rarity": 1,
    "accent": "#4a92c5",
    "accent565": 19608,
    "bHp": 20,
    "bAtk": 10,
    "bDef": 55,
    "bSpe": 80,
    "biome": 1
  },
  {
    "id": 130,
    "name": "GYARADOS",
    "name_ko": "갸라도스",
    "name_ja": "ギャラドス",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#4a92c5",
    "accent565": 19608,
    "bHp": 95,
    "bAtk": 125,
    "bDef": 79,
    "bSpe": 81,
    "biome": 1
  },
  {
    "id": 131,
    "name": "LAPRAS",
    "name_ko": "라프라스",
    "name_ja": "ラプラス",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 2,
    "accent": "#4a92c5",
    "accent565": 19608,
    "bHp": 130,
    "bAtk": 85,
    "bDef": 80,
    "bSpe": 60,
    "biome": 1
  },
  {
    "id": 132,
    "name": "DITTO",
    "name_ko": "메타몽",
    "name_ja": "メタモン",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 2,
    "accent": "#8c8a6b",
    "accent565": 35917,
    "bHp": 48,
    "bAtk": 48,
    "bDef": 48,
    "bSpe": 48,
    "biome": 0
  },
  {
    "id": 133,
    "name": "EEVEE",
    "name_ko": "이브이",
    "name_ja": "イーブイ",
    "evolvesTo": 134,
    "evolveLevel": 30,
    "rarity": 1,
    "accent": "#8c8a6b",
    "accent565": 35917,
    "bHp": 55,
    "bAtk": 55,
    "bDef": 50,
    "bSpe": 55,
    "biome": 0
  },
  {
    "id": 134,
    "name": "VAPOREON",
    "name_ko": "샤미드",
    "name_ja": "シャワーズ",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#4a92c5",
    "accent565": 19608,
    "bHp": 130,
    "bAtk": 65,
    "bDef": 60,
    "bSpe": 65,
    "biome": 1
  },
  {
    "id": 135,
    "name": "JOLTEON",
    "name_ko": "쥬피썬더",
    "name_ja": "サンダース",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#bd9608",
    "accent565": 48289,
    "bHp": 65,
    "bAtk": 65,
    "bDef": 60,
    "bSpe": 130,
    "biome": 0
  },
  {
    "id": 136,
    "name": "FLAREON",
    "name_ko": "부스터",
    "name_ja": "ブースター",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#ef513a",
    "accent565": 60039,
    "bHp": 65,
    "bAtk": 130,
    "bDef": 60,
    "bSpe": 65,
    "biome": 3
  },
  {
    "id": 137,
    "name": "PORYGON",
    "name_ko": "폴리곤",
    "name_ja": "ポリゴン",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 2,
    "accent": "#8c8a6b",
    "accent565": 35917,
    "bHp": 65,
    "bAtk": 60,
    "bDef": 70,
    "bSpe": 40,
    "biome": 0
  },
  {
    "id": 138,
    "name": "OMANYTE",
    "name_ko": "암나이트",
    "name_ja": "オムナイト",
    "evolvesTo": 139,
    "evolveLevel": 40,
    "rarity": 2,
    "accent": "#94823a",
    "accent565": 37895,
    "bHp": 35,
    "bAtk": 40,
    "bDef": 100,
    "bSpe": 35,
    "biome": 1
  },
  {
    "id": 139,
    "name": "OMASTAR",
    "name_ko": "암스타",
    "name_ja": "オムスター",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#94823a",
    "accent565": 37895,
    "bHp": 70,
    "bAtk": 60,
    "bDef": 125,
    "bSpe": 55,
    "biome": 1
  },
  {
    "id": 140,
    "name": "KABUTO",
    "name_ko": "투구",
    "name_ja": "カブト",
    "evolvesTo": 141,
    "evolveLevel": 40,
    "rarity": 2,
    "accent": "#94823a",
    "accent565": 37895,
    "bHp": 30,
    "bAtk": 80,
    "bDef": 90,
    "bSpe": 55,
    "biome": 1
  },
  {
    "id": 141,
    "name": "KABUTOPS",
    "name_ko": "투구푸스",
    "name_ja": "カブトプス",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#94823a",
    "accent565": 37895,
    "bHp": 60,
    "bAtk": 115,
    "bDef": 105,
    "bSpe": 80,
    "biome": 1
  },
  {
    "id": 142,
    "name": "AERODACTYL",
    "name_ko": "프테라",
    "name_ja": "プテラ",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 2,
    "accent": "#94823a",
    "accent565": 37895,
    "bHp": 80,
    "bAtk": 105,
    "bDef": 65,
    "bSpe": 130,
    "biome": 4
  },
  {
    "id": 143,
    "name": "SNORLAX",
    "name_ko": "잠만보",
    "name_ja": "カビゴン",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 2,
    "accent": "#8c8a6b",
    "accent565": 35917,
    "bHp": 160,
    "bAtk": 110,
    "bDef": 65,
    "bSpe": 30,
    "biome": 0
  },
  {
    "id": 144,
    "name": "ARTICUNO",
    "name_ko": "프리져",
    "name_ja": "フリーザー",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 3,
    "accent": "#4ab6c5",
    "accent565": 19896,
    "bHp": 90,
    "bAtk": 85,
    "bDef": 100,
    "bSpe": 85,
    "biome": 5
  },
  {
    "id": 145,
    "name": "ZAPDOS",
    "name_ko": "썬더",
    "name_ja": "サンダー",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 3,
    "accent": "#bd9608",
    "accent565": 48289,
    "bHp": 90,
    "bAtk": 90,
    "bDef": 85,
    "bSpe": 100,
    "biome": 0
  },
  {
    "id": 146,
    "name": "MOLTRES",
    "name_ko": "파이어",
    "name_ja": "ファイヤー",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 3,
    "accent": "#ef513a",
    "accent565": 60039,
    "bHp": 90,
    "bAtk": 100,
    "bDef": 90,
    "bSpe": 90,
    "biome": 3
  },
  {
    "id": 147,
    "name": "DRATINI",
    "name_ko": "미뇽",
    "name_ja": "ミニリュウ",
    "evolvesTo": 148,
    "evolveLevel": 30,
    "rarity": 2,
    "accent": "#5a51c5",
    "accent565": 23192,
    "bHp": 41,
    "bAtk": 64,
    "bDef": 45,
    "bSpe": 50,
    "biome": 1
  },
  {
    "id": 148,
    "name": "DRAGONAIR",
    "name_ko": "신뇽",
    "name_ja": "ハクリュー",
    "evolvesTo": 149,
    "evolveLevel": 55,
    "rarity": 0,
    "accent": "#5a51c5",
    "accent565": 23192,
    "bHp": 61,
    "bAtk": 84,
    "bDef": 65,
    "bSpe": 70,
    "biome": 1
  },
  {
    "id": 149,
    "name": "DRAGONITE",
    "name_ko": "망나뇽",
    "name_ja": "カイリュー",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 0,
    "accent": "#5a51c5",
    "accent565": 23192,
    "bHp": 91,
    "bAtk": 134,
    "bDef": 95,
    "bSpe": 80,
    "biome": 1
  },
  {
    "id": 150,
    "name": "MEWTWO",
    "name_ko": "뮤츠",
    "name_ja": "ミュウツー",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 3,
    "accent": "#d6517b",
    "accent565": 53903,
    "bHp": 106,
    "bAtk": 110,
    "bDef": 90,
    "bSpe": 130,
    "biome": 0
  },
  {
    "id": 151,
    "name": "MEW",
    "name_ko": "뮤",
    "name_ja": "ミュウ",
    "evolvesTo": 0,
    "evolveLevel": 0,
    "rarity": 3,
    "accent": "#d6517b",
    "accent565": 53903,
    "bHp": 100,
    "bAtk": 100,
    "bDef": 100,
    "bSpe": 100,
    "biome": 0
  }
];

function getDexName(id, lang = 'ko') {
  if (id <= 0 || id > DEX_COUNT) return '?';
  const entry = DEX_TBL[id];
  if (!entry) return '?';
  if (lang === 'ko') return entry.name_ko;
  if (lang === 'ja') return entry.name_ja;
  return entry.name;
}
